site_name: IoTxWeb3 Intelligence Platform (IW3IP)
site_description: Official website for IoTxWeb3 Intelligence Platform (IW3IP)
site_url: https://ertlnagoya.github.io/iw3ip.github.io/
repo_name: ertlnagoya/iw3ip.github.io
repo_url: https://github.com/ertlnagoya/iw3ip.github.io
exclude_docs: README.md

theme:
  name: material
  language: ja
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.highlight
    - content.code.copy

plugins:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
          nav_translations:
            Home: ホーム
            Platform Overview: プラットフォーム概要
            Publications: 論文
            Docs: ドキュメント
        - locale: en
          name: English
          build: true
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Platform Overview: platform-overview.md
  - Publications: publications.md
  - Docs: docs.md
